#include<iostream.h>
#include<stdlib.h>
#include<conio.h>
//using namespace std ;

int main()
{ clrscr();
 float y,x;
   int i;
  y=rand() ;
 cout<<"think any no."<<endl;
 getch();
 cout<<" make it twice \n";
 getch();
 cout<<"now add "<<y<<" to your result \n";
 getch();

 cout<<"then make it half \n"<<"now subtract the no. that you was thought";
 getch();


for(i=1;i<=100;++i)
 {
     cout<<".."<<endl;
 }
 cout<<"\n And your ans. is "<<y/2;
 getch();


    return 0;

}
