#include<iostream.h>
#include<stdio.h>
struct emp
{
int empno;
char name[26];
char desig[16];
float basic;
}
void main()
{
for(int i=0;i<10;i++)
{cout<<"\n"<<"employee no:";
cin>>sales_emp[i].empno;
cout<<"\n"<<"employee name:";
gets(sales_emp[i].name);
cout<<"\n"<<"designation:";
gets(sales_emp[i].desig);
cout<<"\n"<<"date of birth:";
cout<<"date:";
cin>>sales_emp[i].dob.date;
cout<<"\n month:";
gets(sales_emp[i].dob.month);
cout<<"\n year:";
gets(sales_emp[i].dob.year);
cout<<"\n"<<"sex:";
gets(sales_emp[i].sex);
cout<<"\n"<<"joining date:";
gets(sales_emp[i].jd);
cout<<"\n"<<"retiring date:";
gets(sales_emp[i].rd);
} return 0;
 }
