
#include<iostream.h>
#include<conio.h>
 void main()
 { clrscr();
   int Roll, Class;
   char Name[50], Sec;
   cout<< "enter your roll no.:";
   cin>> Roll;
   cout<< "enter your name:  ";
   cin>> Name;
   cout<< "enter your class:  ";
   cin>> Class;
   cout<< "Enter your section:  ";
   cin>> Sec;
   cout<<"\n output _____";
   cout<<"\n "<< Name;
   cout<<"\n "<<Class;
   cout<<"\n "<<Sec;
   getch();
   }