#include<iostream.h>
#include<conio.h>
#include<process.h>
#include<iomanip.h>
void main()
{
clrscr()
int ch;
cout<<"______main manu_______";
cout<<"______Periodic table__";
cout<<"\n\n\t 1. S Block";
cout<<"\t 2. P Block";
cout<<"\t 3. D Block";
cout<<"\t 4. F Block";
cout<<"\t 5.Exit";
cout<<"Enter your choice:";
cin>>ch;
int s[10];
switch()
{

case1:
for(int i=0;i<=10;i++)
{
cout<<"element of s block=";
cin>>s[i];
break;
case2:
cout<<"enter the elemnt of p block=";
break;
case3
