#include<iostream.h>
#include<stdio.h>
#include<stdlib.h>
const int WAN=30;
class employee{private:
		       char int[WAN];
		       Unsignedlong enumb
		public:
		       void getdata()
		      {cout<<"enter name:";
		      gets(name);
		      cout<<"enter employee number :";
		      cin>>enumb;
		      }
		      void putdata()
		      {cout<<"name:"<<name<<"\t";
		      cin<<emp.number<<enumb<<"\t";
		      cout<<"basic sal:"<<basic;
		      }
		      class manager:private employee
		      {
		      private:
		      char title[WEN];
		      Publi
