#include<iostream.h>
#include<conio.h>
#include<process.h>
void main()
{
clrscr();
char ch;
cout<<"\tMAIN-MENU";
cout<<"\n\nChoose an OPTION:";
cout<<"\n1.Fuck(F/f)";
cout<<"\n2.Suck(S/s)";
cout<<"\nGet away(G/g)";
cout<<"\n\nEnter choice:";
cin>>ch;
if(ch=='F'||ch=='f')
{
cout<<"\nHurrah!!!!!!!!!!";
cout<<"\n\nYou have win a chance to fuck randikhana at Manduadih";
cout<<"\n\nPrint this reciept and fuck there";
}
if(ch=='S'||ch=='s')
{
cout<<"\nHurrah!!!!!!!!!!";
cout<<"\n\nYou had win a chance to suck and smooch at your location";
cout<<"\nGet location from Mndudih";
}
if(ch=='G'||ch=='g')
exit(0);
getch();
}