#include<iostream.h>
#include<conio.h>
void main()
{
clrscr();
int dow;
cout<<"Enter the number of weeks(1-7):";
cin>>dow;
switch(dow)
{
case 1 : cout<<"Monday";
break;
case 2 : cout<<"Tuesday";
break;
case 3 : cout<<"Wednesday";
break;
case 4 : cout<<"Thursday";
break;
case 5 : cout<<"Friday";
break;
case 6 : cout<<"Saturday";
break;
case 7 : cout<<"Sunday";
break;
default : cout<<"Wrong number of day";
}
}