//get all the table at there ???????????????
#include<iostream.h>
#include<conio.h>
int main()
{   clrscr();
    int number,multiple1,multiple2,multiple3,multiple4,multiple5,multiple6,multiple7,multiple8,multiple9,multiple10;
    cout<<"enter a number:";
    cin>>number;
    multiple1 =number*1;
    multiple2 =number*2;
    multiple3 =number*3;
    multiple4 =number*4;
    multiple5 =number*5;
    multiple6 =number*6;
    multiple7 =number*7;
    multiple8 =number*8;
    multiple9 =number*9;
    multiple10 =number*10;
    cout<<"first ten steps of given numbers are:";
    cout<<multiple1<<","<< multiple2<<","<<multiple3<<","<<multiple4<<"."<<multiple5<<","<<multiple6<<","<<multiple7<<","<<multiple8<<","<<multiple9<<","<<multiple10;
    getch();
     return 0;
}

