#include<iostream.h>
#include<conio.h>
#include<math.h>
void main()
{clrscr();
int a,b , c,root1,root2;
cout<<"enter the value of a,b,cin the quadratic equation ax^+bx+c;
cin>>a>>b>>c;
if(!a)
cout<<"the value of\'a\' should be not zero"
<<"aborting!!!!!;
else
{delta=b*b-4*a*c;
if(delta>0)
{cout<<"roots are real and unequal";
root1=(-b+sqrt(delta))/2(*a);
root=(-b-sqrt(delta))/2(*a);
cout<<roots are realand unequal"<<\n";
cout<<"roots1="<<root1
cout<<"root2="<<root2<<\n;
}
else if(delta==o)
}